- docs/UserGuide.adoc
Cleaned up UG and added v1.1 tag. Resolves #15
> Version 1.1

- src/main/java/seedu/address/logic/commands/LoginCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/LoginCommandParser.java
- src/main/java/seedu/address/model/person/LoginCredentialsPredicate.java
- src/main/java/seedu/address/ui/HelpWindow.java
Functioning login logic from CLI input. Resolves #57
> Basic Login Implementation

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/model/tag/Tag.java
Proposed alternative to resolve #63
> Added Support for Dashes & Dots to Tags

- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/LoginCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlySession.java
- src/main/java/seedu/address/model/Session.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
You can use the model passed to command to retrieve the logged in person using `model.getLoggedInPerson()` which will return you a person object (or null if no one is logged in) @tirameshu @atharvjoshi 
Resolves #54
> Added Session Functionality

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/UiManager.java
- src/main/resources/view/IncidentListPanel.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/VehicleListPanel.fxml
App loads with only person panel visible, then switches to incidents and vehicles after login. Closes #40, resolves #51 by setting prefHeight of all the panels to current 4k resolution limits.
> Implemented Login GUI Effect

- src/main/java/seedu/address/logic/commands/LoginCommand.java
> Fixed Empty Display when Invalid Login

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlySession.java
- src/main/java/seedu/address/model/Session.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/StatusBarFooter.fxml
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Resolves #41, #70. Changed `Model.getLoggedInPerson()` to `Model.getSession()` which now returns a `Session` object instead of a `Person`. Created `Logic.getSession()` which retrieves the session from the model for GUI utility. @tirameshu @atharvjoshi take note for autofill purposes.
> Added Session Details to Status Bar

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/StatusBarFooter.fxml
Implementation taken from: https://github.com/se-edu/addressbook-level4/blob/master/src/main/resources/view/StatusBarFooter.fxml
> Improved Status Bar UI

- src/main/java/seedu/address/logic/commands/SubmitCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
> Adding SubmitCommand

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/LoginCommand.java
- src/main/java/seedu/address/logic/commands/LogoutCommand.java
- src/main/java/seedu/address/logic/commands/SwapCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Added logout command which logs a user out, and a swap command to swap GUI interface between persons and incidents view. Inserted guard statement in LogicManager.java to restrict command access prior to login. Resolves #65, resolves #55
> Added Logout and Swap Commands

- src/main/java/seedu/address/logic/commands/SearchIncidentsCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/SearchIncidentsCommandParser.java
- src/main/java/seedu/address/model/incident/NameKeywordsPredicate.java
> Add incident search operator flag

- src/main/java/seedu/address/logic/commands/SearchIncidentsCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/SearchIncidentsCommandParser.java
- src/test/java/seedu/address/logic/parser/SearchIncidentsCommandParserTest.java
> Update search variable names

- docs/DeveloperGuide.adoc
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
Completed week 10 deliverable for DG updates. Resolves #96, Resolves #119
> Update Developer Guide

- docs/DeveloperGuide.adoc
Summary of incident filling and submitting feature.
> Initial update to developer guide.

- src/main/java/seedu/address/logic/commands/ListVehiclesCommand.java
- src/main/java/seedu/address/model/Model.java
> Fix vehicles listing command

- src/main/java/seedu/address/logic/commands/FindVehiclesCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/FindVehiclesCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/vehicle/VNumKeywordsPredicate.java
- src/main/java/seedu/address/model/vehicle/VTypeKeywordsPredicate.java
> Search vehicles by vtype and vnum

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/LogoutCommand.java
- src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlySession.java
- src/main/java/seedu/address/model/Session.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/parser/IncidentManagerParserTest.java
> Updated User Guide and Other Improvements

- src/main/java/seedu/address/logic/commands/FillCommand.java
- src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
- src/main/java/seedu/address/logic/commands/SubmitCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/FillCommandParser.java
- src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/SubmitCommandParser.java
- src/main/java/seedu/address/model/IncidentManager.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/incident/CallerNumber.java
- src/main/java/seedu/address/model/incident/Incident.java
- src/main/java/seedu/address/model/incident/IncidentDateTime.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedIncident.java
- src/test/data/JsonSerializableIncidentManagerTest/duplicatePersonIncidentManager.json
- src/test/data/JsonSerializableIncidentManagerTest/invalidEntityIncidentManager.json
- src/test/data/JsonSerializableIncidentManagerTest/invalidPersonIncidentManager.json
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
- src/test/java/seedu/address/model/incident/IncidentDateTimeTest.java
- src/test/java/seedu/address/testutil/IncidentBuilder.java
- src/test/java/seedu/address/testutil/TypicalEntities.java
Main change: DateTime in a more readable format. Got rid of all redundant constructors in Incident class except one (the constructor used by @hellopanda128 for edit command).
> Improve implementation of Incident class

- src/main/java/seedu/address/logic/commands/FillCommand.java
- src/main/java/seedu/address/logic/commands/NewCommand.java
- src/main/java/seedu/address/logic/commands/SubmitCommand.java
- src/main/java/seedu/address/model/IncidentManager.java
- src/main/java/seedu/address/model/ReadOnlyIncidentManager.java
- src/main/java/seedu/address/model/incident/Incident.java
- src/main/java/seedu/address/model/incident/UniqueIncidentList.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedIncident.java
- src/main/java/seedu/address/storage/JsonSerializableIncidentManager.java
- src/main/java/seedu/address/ui/IncidentCard.java
- src/main/resources/view/IncidentListCard.fxml
- src/test/java/seedu/address/testutil/TypicalEntities.java
resolves #114.
- Add 'status' badge to visualise changes in incident status brought about by `fill` and `submit` commands.
- Improved incident panel layout makes the GUI more reader-friendly.
> Improve Incident Panel GUI

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
- src/main/java/seedu/address/logic/commands/FindPersonsCommand.java
- src/main/java/seedu/address/logic/commands/FindVehiclesCommand.java
- src/test/java/seedu/address/logic/commands/FindPersonsCommandTest.java
- src/test/java/seedu/address/logic/commands/FindVehiclesCommandTest.java
> Fix search return message for either one or zero returned incidents, persons and vehicles

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
- src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
> Abstract messages from ListIncidentsCommand to Message

- src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
- src/main/java/seedu/address/logic/commands/EditIncidentCommand.java
- src/main/java/seedu/address/logic/parser/AddVehicleCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/incident/Incident.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/testutil/IncidentBuilder.java
and remove redundant incident constructor
> Add add-v command for adding vehicles

- src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
- src/main/java/seedu/address/logic/commands/DeleteVehicleCommand.java
- src/main/java/seedu/address/logic/commands/EditVehicleCommand.java
- src/main/java/seedu/address/logic/parser/EditVehicleCommandParser.java
> bug fixes to edit-v command

- src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
Resolves #180 and resolves #203
Can be tested using: `find-i self`
> Add self-search for find-incidents

- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/parser/NewCommandParser.java
- src/main/java/seedu/address/storage/JsonAdaptedIncident.java
- src/main/java/seedu/address/storage/StorageManager.java
to acc for drafts where attributes like desc and caller number are yet to be initialised
> updated json adapted incident

- src/main/java/seedu/address/storage/JsonAdaptedIncident.java
> setting dummy variables for caller num n desc instead of leaving blank

- src/main/java/seedu/address/logic/commands/VehicleAssignmentCommand.java
Letting user know if there are vehicles in the area before prompting for auto/n.
Resolves #253
> Checks for available vehicle before prompt for auto/n

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
- src/main/java/seedu/address/logic/parser/FindVehiclesCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/vehicle/VNumKeywordsPredicate.java
- src/main/java/seedu/address/model/vehicle/VehicleNumber.java
- src/main/java/seedu/address/model/vehicle/VehicleType.java
- src/test/java/seedu/address/logic/commands/FindVehiclesCommandTest.java
- src/test/java/seedu/address/testutil/TypicalVehicles.java
> adding vnum validation, and made vtype, auto args case insensitive

- docs/UserGuide.adoc
> Adding instruction on district number in UG

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
- src/main/java/seedu/address/logic/commands/EditIncidentCommand.java
- src/main/java/seedu/address/logic/commands/EditVehicleCommand.java
- src/main/java/seedu/address/model/incident/Incident.java
- src/main/java/seedu/address/model/vehicle/VehicleNumber.java
- src/test/java/seedu/address/logic/commands/EditIncidentCommandTest.java
- src/test/java/seedu/address/testutil/EditIncidentBuilder.java
- src/test/java/seedu/address/testutil/IncidentUtil.java
and minor edits to user guide. resolves #248 #249 #247 #239
> Add vehicle number validation when adding vehicles

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
- src/main/java/seedu/address/logic/commands/DeleteVehicleCommand.java
- src/main/java/seedu/address/logic/commands/EditVehicleCommand.java
- src/main/java/seedu/address/logic/parser/EditVehicleCommandParser.java
- src/main/java/seedu/address/model/vehicle/VehicleNumber.java
> Fix vehicle number duplication when adding and deleting vehicles

- src/main/java/seedu/address/logic/commands/EditVehicleCommand.java
- src/main/java/seedu/address/logic/parser/EditVehicleCommandParser.java
- src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
resolves #233 
resolves #232 
resolves #223
> Resolve PED errors

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
> More specific exception msg for auto

- src/main/java/seedu/address/logic/parser/CliSyntax.java
> changing prefix of district

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/ListVehiclesCommand.java
- src/main/java/seedu/address/logic/commands/NewCommand.java
- src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
- src/main/java/seedu/address/logic/parser/NewCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/NewCommandTest.java
- src/test/java/seedu/address/testutil/TypicalVehicles.java
for parseAuto, parseDistrict, parseVType, parseVNum, parseDistricts.
also added tests for new command. Resolves #271
> Detecting irrelevant prefixes

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/LoginCommand.java
- src/main/java/seedu/address/logic/parser/LoginCommandParser.java
- src/main/java/seedu/address/model/person/LoginCredentialsPredicate.java
- src/test/java/seedu/address/logic/commands/FindPersonsCommandTest.java
- src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
- src/test/java/seedu/address/logic/commands/LoginCommandTest.java
- src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
- src/test/java/seedu/address/logic/commands/SwapCommandTest.java
- src/test/java/seedu/address/logic/parser/FindPersonsCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ListPersonsCommandParserTest.java
- src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
> Added Tests for Features

- docs/DeveloperGuide.adoc
- src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Added Tests for List Persons

- docs/AboutUs.adoc
Updated my name in AboutUs page to reflect full name in LumiNUS as per week 13 [submission guidelines](https://nus-cs2103-ay1920s1.github.io/website/schedule/week13/project.html) for product website. @Yoshi275 @atharvjoshi @tirameshu @hellopanda128 please update your own names at your convenience thanks :)
> Updated Name in AboutUs

- src/main/java/seedu/address/model/vehicle/Vehicle.java
- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/resources/view/MainWindow.fxml
Allow for flexible result display box: Resolves #288 
Change app name to Incident Manager: Resolves #287 
Add spacing to Vehicle display in Incident GUI: Resolves #241
> Modify GUI with minor changes

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/madanalogy.adoc
Updated DG image widths for PPP page requirements
> Minor DG Update

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/commands/UpdateCommand.java
- src/main/java/seedu/address/model/person/Username.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
> added admin account if storage error

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/madanalogy.adoc
- src/main/java/seedu/address/model/util/SampleDataUtil.java
> added more sample accounts

- src/main/java/seedu/address/logic/commands/FindVehiclesCommand.java
- src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
- src/main/java/seedu/address/model/vehicle/VehicleType.java
- src/test/java/seedu/address/logic/commands/VehicleAssignmentCommandTest.java
- src/test/java/seedu/address/logic/parser/FindVehiclesCommandParserTest.java
> Adding basic tests for find-v parser

- src/main/java/seedu/address/model/incident/DescriptionKeywordsPredicate.java
- src/main/java/seedu/address/model/incident/IdKeywordsPredicate.java
- src/main/java/seedu/address/model/incident/NameKeywordsPredicate.java
> Establish assertions in predicate search

- src/main/java/seedu/address/ui/IncidentCard.java
> Change GUI for Last Modified User Display

- src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
- src/main/java/seedu/address/model/incident/Description.java
- src/main/java/seedu/address/model/incident/DescriptionKeywordsPredicate.java
- src/main/java/seedu/address/model/incident/IncidentId.java
> Fix empty input for find-i

- src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
- src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
- src/test/java/seedu/address/testutil/TypicalIncidents.java
> Add List Command test cases

- src/test/java/seedu/address/logic/commands/FindIncidentsCommandTest.java
- src/test/java/seedu/address/testutil/TypicalIncidents.java
> Add Find Command testing

- docs/DeveloperGuide.adoc
> removed product survey
